KryptoWebUI/Controllers/EntityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KryptoInterface.Interface;
using Microsoft.AspNetCore.Mvc;

namespace KryptoWebUI.Controllers
{
    public class EntityController : Controller
    {
        IModeLayer ModeLayer;
        public EntityController(IModeLayer modeLayer)
        {
            ModeLayer = modeLayer;
        }
        public IActionResult List(String Entity)
        {
           // ModeLayer.GetEntity()

            return View();
        }
    }
}

KryptoWebUI/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KryptoInterface.Interface;
using Microsoft.AspNetCore.Mvc;

namespace KryptoWebUI.Controllers
{
    public class MainController : Controller
    {
        
        public MainController(IModeLayer modeLayer)
        {
            
            
        }
        public IActionResult List()
        {         
            return View();
        }
    }
}

KryptoWebUI/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KryptoInterface.Interface;
using Microsoft.AspNetCore.Mvc;
using KryptoModel.Model;
using System.Reflection;

namespace KryptoWebUI.Controllers
{
    public class TableController : Controller
    {
        IModeLayer ModeLayer;
        public TableController(IModeLayer modeLayer)
        {
            ModeLayer = modeLayer;
        }

        public IActionResult Entity(String type, String Id)
        {
            IEnumerable<ITable> tables = ModeLayer.GetTable();
            if (type == null)
            {
                return View("List", tables);
            }
            Type typeModel=null;
            Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
            foreach (Assembly ass in assemblies)
            {
                typeModel = ass.GetType(type);
                if(typeModel!=null)
                {
                    break;
                }

            }
            if (typeModel != null)
            {
                ITable table = tables.Where(r => typeModel.IsSubclassOf(r.TypeEntity) || typeModel== r.TypeEntity).FirstOrDefault();
                IMyEntity myEntities = ModeLayer.GetEntity(table.TypeEntity).Where(r=>r.Id.ToString()== Id).FirstOrDefault();
                if (myEntities != null)
                {
                    return View(myEntities);
                }
            }
            return View("List", tables);
        }
    }
}

KryptoWebUI/Controllers/TableListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KryptoInterface.Interface;
using Microsoft.AspNetCore.Mvc;
using KryptoModel.Model;
using System.Reflection;

namespace KryptoWebUI.Controllers
{
    public class TableListController : Controller
    {
        IModeLayer ModeLayer;
        public TableListController(IModeLayer modeLayer)
        {
            ModeLayer = modeLayer;
        }
       /* public IActionResult List()
        {
          IEnumerable<ITable> tables=  ModeLayer.GetTable();
            return View(tables);
        }*/
        public IActionResult List()
        {
           
                IEnumerable<ITable> tables = ModeLayer.GetTable();
                return View(tables);
            

        }
        public IActionResult Table(String type)
        {
            IEnumerable<ITable> tables = ModeLayer.GetTable();
            if (type == null)
            {
                return View("List", tables);
            }            
            IEnumerable<ITable> table = tables.Where(r => r.TypeEntity.Name == type);


            if (table.Count() == 1)
            {
               IEnumerable<IMyEntity> myEntities= ModeLayer.GetEntity(table.FirstOrDefault().TypeEntity);
                IMyEntity myEntity = myEntities.FirstOrDefault();




                return View(myEntities);
            }
            else
            {
                return View("List", tables);
            }


        }

    }
}

KryptoWebUI/Views/Main/List.cshtml
    <div>
        <a asp-controller="Main" asp-action="List"> <h3>Home</h3></a>
        <a asp-controller="TableList" asp-action="List"><h3>Список таблиц</h3></a>
    </div>

KryptoWebUI/Views/Shared/Property.cshtml
@model System.Reflection.PropertyInfo

<h3> @Model.Name </h3>
<h3> @ViewBag.Model </h3>

KryptoWebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>Angular QuickStart</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Загрузка библиотек -->
    <!-- Polyfill(s) для старых браузеров -->
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <!--Настройка SystemJS -->
    <script src="systemjs.config.js"></script>

    <script>
      System.import('app').catch(function(err){
          console.error(err);
        });
    </script>
</head>

<!--Отображение приложения -->
<body>
    <my-app>Loading...</my-app>
      @RenderBody()
       <!--Для запуска приложения откройте командную строку и выполните команду "npm start"-->
</body>

</html>

KryptoWebUI/Views/Table/Entity.cshtml
@model IMyEntity
<div>
    <h3> @Model.ToString() </h3>

    @foreach (System.Reflection.PropertyInfo prop in Model.GetType().GetProperties())
    {
    <p>
        <label> @prop.Name  </label>
        <input value=" @prop.GetValue(Model)" asp-for="@prop.Name" disabled="disabled" />

        @if (prop.CanWrite)
        {

            <buttot>Edit</buttot>
        }
    </p>
    }

</div>

KryptoWebUI/Views/Table/List.cshtml
@model IEnumerable<IMyEntity>

@foreach (IMyEntity Entity in Model)
{
    <div>
        <h3> @Entity.ToString() </h3>
    </div>

}

KryptoWebUI/Views/TableList/List.cshtml
@model IEnumerable<ITable>
@foreach(var p in Model)
{
    <div>
        <a  asp-action="Table"  asp-route-type=@p.TypeEntity.Name><h3>@p.TypeEntity.Name</h3></a>   
    </div>

}

KryptoWebUI/Views/TableList/Table.cshtml
@model IEnumerable<IMyEntity>

@foreach (IMyEntity Entity in Model)
{
<div>
    <a asp-controller="Table" asp-action="Entity" asp-route-type=@Entity.GetType() asp-route-Id=@Entity.Id ><h3>@Entity.ToString()</h3></a>    
</div>
    

}